export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_GET_INFO = "AUTH_GET_INFO";
export const AUTH_GET_INFO_SUCCESS = "AUTH_GET_INFO_SUCCESS";
export const AUTH_GET_INFO_FAILURE = "AUTH_GET_INFO_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_LEAVE = "AUTH_LEAVE";
export const AUTH_LEAVE_SUCCESS = "AUTH_LEAVE_SUCCESS";
export const AUTH_LEAVE_FAILURE = "AUTH_LEAVE_FAILURE";

export const POST_CREATE = "POST_CREATE";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAILURE = "POST_CREATE_FAILURE";

export const POST_GET_BY_USER = 'POST_GET_BY_USER';
export const POST_GET_BY_USER_SUCCESS = 'POST_GET_BY_USER_SUCCESS';
export const POST_GET_BY_USER_FAILURE = 'POST_GET_BY_USER_FAILURE';

export const POST_GET_BY_ID = 'POST_GET_BY_ID';
export const POST_GET_BY_ID_SUCCESS = 'POST_GET_BY_ID_SUCCESS';
export const POST_GET_BY_ID_FAILURE = 'POST_GET_BY_ID_FAILURE';



